//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class J_TEST
    {
        public decimal TEST_ID { get; set; }
        public string MATERIAL_NO { get; set; }
        public string CATEGORY_CODE { get; set; }
    }
}
